# Generated by Django 4.1.7 on 2023-04-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerApp', '0007_alter_flower_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
